### ISSUE TITLE
Actividad 4 Mapa mental

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Proyect-A16#2]
[Mapa mental de conjuntos.pdf](https://github.com/user-attachments/files/17099058/Mapa.mental.de.conjuntos.pdf)

**Comment by Kevin-bit-cm** [comment]
Manejo conceptual y dominio del tema: 4/5
Relación entre los conceptos incluidos en el tema: 4/5
Calidad de la presentación: 5/5
Jerarquía : 4/5
Calf: 17 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
